### ISSUE TITLE
Rodapé

### ISSUE THREAD

**Issue by frenktico** [CursinhoTransFormacao/landing#11]
A parte mais difícil de todas - okay, brincadeiras à parte -, final do site conforme o layout. Abaixo segue o bloco de código:

```
<p>/CursinhoPopularTransformação</p>
<p>cursinhopopulartrans@gmail.com</p>
<p>CRD SP - Rua Major Sertório, 292/294 - República -  São Paulo</p>
```

**Comment by brunoluizgr** [comment]
Estou desenvolvendo esta parte também, :D

**Comment by frenktico** [comment]
Encerrando o issue por estar resolvido.
