### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by frenktico** [CursinhoTransFormacao/landing#20]
Menu não está aparecendo corretamente e telas MD e SM

**Comment by frenktico** [comment]
Acredito que está no CSS a partir da seção `/*==========  Método Non-Mobile   ==========*/`

**Comment by arbolitoloco** [comment]
Vou trabalhar nisso.

**Comment by arbolitoloco** [comment]
Será que tem como você criar um branch especificamente para o menu, por favor? Acho que facilitaria na hora de mesclar, para evitar conflitos. Que tal?

**Comment by frenktico** [comment]
@arbolitoloco o issue há está criado! ;)
