### ISSUE TITLE
Galeria de imagens

### ISSUE THREAD

**Issue by frenktico** [CursinhoTransFormacao/landing#21]
É preciso rever a galeria de imagens a ser inserida no site para um modelo melhor.

**Comment by frenktico** [comment]
@gionaufal você tinha mostrado aquele modelo e acredito ser interessante para as imagens. Consegue implementá-lo?

**Comment by gionaufal** [comment]
Opa, claro! Implemento hoje. Você já tem algum padrão de tamanho de imagem?
