### ISSUE TITLE
Menu Topo

### ISSUE THREAD

**Issue by frenktico** [CursinhoTransFormacao/landing#5]
O menu deve acompanhar o rolamento da página. No layout a distribuição está clara, se houver dúvida por favor informe. Para facilitar, o código a ser trabalhado é este:

```
<img src="imgs/logotipo_cursinho.png" width="100px" heigth="100px" alt="logotipo Cursinho Popular TransFormação">

<ul>
  <li>HOME</li>
  <li>SOBRE</li>
  <li>IMAGENS</li>
  <li>CONTATO</li>
</ul>
```

**Comment by arbolitoloco** [comment]
Dei uma formatada geral, mas ajustes podem ser necessários. Alterei o tamanho do logo no HTML.

**Comment by frenktico** [comment]
Considerando finalizado já que agora faltam alguns ajustes (tamanho e links).
